module.exports=function(grunt){
	grunt.initConfig({
		pkg:grunt.file.readJSON('package.json'),
		concat:{
			options:{
				separator:';'
			},
			dist:{
				src:['js/myown.js'],
				dest:'dist/myown.min.js'
			}
		},
		uncss:{
			dist:{
				files:[
				{src:'index.html',dest:'dist/myown.css'}
				]
			}
		},
		uglify:{
			my_target:{
				files:{
					'dist/myown.js':['js/myown.js']
				}
			}
		},
		jshint:{
			files:['Gruntfile.js','js/*.js'],
			options:{
				globals:
				{
					jQuery:true,
					console:true,
					module:true,
					document:true
				}
			}
		},
		htmlmin:{
			dist:{
				options:{
					removeComments:true,
					collapseWhitespace:true
				},
				files:{
					'dist/index.html':'index.html'
				}
			}
		},
		htmllint: {
			all:['index.html']
		},
		csslint:{
			src:['css/main.css']
		},
		imageoptim:
		{
			myTask:{
				options:{
					jpegMini:false,
					imageAlpha:true,
					quitAfter:true
				},
				src:['images']
			}
		},
		cssmin:{
			target: {
				files:[
					{
						src:'css/main.css',
						dest:'dist/myown.css'
					}
				]
			}
		},
		concat_css:{
			options:{

			},
			all:{
				src:["css/*.css"],
				dest:"dist/main.css"
			}
		},
		autoprefixer:{
			multiply_files:{
				expand:true,
				flatten:true,
				src:"css/*css",
				dest:"dist/"
			}
		},
		uncss:{
			dist:{
				files:{
					'dist/myown.css':['index.html']
				}
			}
		},
		watch:{
			files:['index.html','css/*.css','js/*.js'],
			tasks:[]
		}
	});   
	grunt.loadNpmTasks('grunt-contrib-uglify');
	grunt.loadNpmTasks('grunt-contrib-jshint');
	grunt.loadNpmTasks('grunt-contrib-concat');
	grunt.loadNpmTasks('grunt-concat-css');
	grunt.loadNpmTasks('grunt-contrib-watch');
	grunt.loadNpmTasks('grunt-imageoptim');
	grunt.loadNpmTasks('grunt-contrib-cssmin');
	grunt.loadNpmTasks('grunt-contrib-htmlmin');
	grunt.loadNpmTasks('grunt-contrib-csslint');
	grunt.loadNpmTasks('grunt-autoprefixer');
	grunt.loadNpmTasks('grunt-uncss');
	grunt.loadNpmTasks('grunt-html');
};
